### ISSUE TITLE
unit plot for dmd in DMDpack

### ISSUE THREAD

**Issue by vinayakumarr** [Benli11/DMDpack#4]
i have tried to plot unit plot for lamda_eigenmodes in DMDpack. The code is given below. I am able to plot unitplot in pyDMD. But in DMD pack, i have modified the code and but the lamda values are not printing on the unit circle.

import numpy as np
from dmd import dmd, cdmd
from dmd import tools
from pydmd import DMD

import scipy.io

mat = scipy.io.loadmat('DATA/FLUIDS/CYLINDER_ALL.mat')

dvotrall = mat['VORTALL']

import numpy as np
from dmd import dmd
from dmd import tools

Fmodes, b, V, omega = dmd(dvotrall, dt=dt, k=15, return_vandermonde=True, return_amplitudes=True, p=10, q=1, modes='standard')

import matplotlib.pyplot as plt

def plot_eigs(v):
    
        show_axes=True
        show_unit_circle=True
        figsize=(8, 8)
        title='vinay'
        plt.figure(figsize=figsize)
        plt.title(title)
        plt.gcf()
        ax = plt.gca()

        points, = ax.plot(v.real, v.imag, 'bo', label='Eigenvalues')

        # set limits for axis
        limit = np.max(np.ceil(np.absolute(v)))
        ax.set_xlim((-limit, limit))
        ax.set_ylim((-limit, limit))

        plt.ylabel('Imaginary part')
        plt.xlabel('Real part')

        if show_unit_circle:
            unit_circle = plt.Circle(
                (0., 0.),
                1.,
                color='green',
                fill=False,
                label='Unit circle',
                linestyle='--')
            ax.add_artist(unit_circle)

        # Dashed grid
        gridlines = ax.get_xgridlines() + ax.get_ygridlines()
        for line in gridlines:
            line.set_linestyle('-.')
        ax.grid(True)

        ax.set_aspect('equal')

        # x and y axes
        if show_axes:
            ax.annotate(
                '',
                xy=(np.max([limit * 0.8, 1.]), 0.),
                xytext=(np.min([-limit * 0.8, -1.]), 0.),
                arrowprops=dict(arrowstyle="->"))
            ax.annotate(
                '',
                xy=(0., np.max([limit * 0.8, 1.])),
                xytext=(0., np.min([-limit * 0.8, -1.])),
                arrowprops=dict(arrowstyle="->"))

        # legend
        if show_unit_circle:
            ax.add_artist(
                plt.legend(
                    [points, unit_circle], ['Eigenvalues', 'Unit circle'],
                    loc=1))
            print('ddsfsdfsd')
        else:
            ax.add_artist(plt.legend([points], ['Eigenvalues'], loc=1))
            print('fsdfs')

        plt.show()

v = np.diag(Fmodes)

plot_eigs(v)

![download](https://user-images.githubusercontent.com/18217467/46965202-cbbc8880-d0c7-11e8-9f08-3dffb10969e7.png)

**Comment by erichson** [comment]
Just do:
```
Fmodes, b, V, omega = dmd(dvotrall, dt=dt, k=15, return_vandermonde=True, return_amplitudes=True, p=10, q=1, modes='standard')
plot_eigs(np.exp(omega))
```
